# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('crisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Decision')),
            ],
        ),
    ]
