# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_decision_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='type_of_crisis',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
