# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_auto_20160319_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
