# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_resourcerequest_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='agency',
        ),
    ]
