# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_remove_notification_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='place',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Place'),
            preserve_default=False,
        ),
    ]
