# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_notification_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='place',
        ),
        migrations.AddField(
            model_name='notification',
            name='agency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Agency'),
        ),
    ]
