# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0008_auto_20160407_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='agency',
        ),
        migrations.AddField(
            model_name='notification',
            name='notify',
            field=models.TextField(default=''),
        ),
    ]
